package com.xworkz.runner;

import com.xworkz.external.*;

public class ExternalRunner {
    public static void main(String[] args) {
        Smartphone smartphone1 = new Smartphone();
        smartphone1.setSmartphone("Apple","iPhone 13",128,true);
        System.out.println(smartphone1);
        Smartphone smartphone2 = new Smartphone();
        smartphone2.setSmartphone("Samsung","Galaxy S21",256,true);
        System.out.println(smartphone2);
        Smartphone smartphone3 = new Smartphone();
        smartphone3.setSmartphone("Samsung","Galaxy S21",256,true);
        System.out.println(smartphone3);
        boolean smartphoneMatch = smartphone1.equals(smartphone2);
        boolean smartphoneNotMatch = smartphone2.equals(smartphone3);
        System.out.println("Smartphone Match: "+ smartphoneMatch);
        System.out.println("Smartphone Not Match:" + smartphoneNotMatch);

        Laptop laptop1 = new Laptop();
        laptop1.setLaptop("Dell","i7",16,15.6);
        System.out.println(laptop1);
        Laptop laptop2 = new Laptop();
        laptop2.setLaptop("HP","i5",8,14.0);
        System.out.println(laptop2);
        Laptop laptop3 = new Laptop();
        laptop3.setLaptop("HP","i5",8,14.0);
        System.out.println(laptop3);
        boolean laptopMatch = laptop1.equals(laptop2);
        boolean laptopNotMatch = laptop2.equals(laptop3);
        System.out.println("Laptop Match: "+ laptopMatch);
        System.out.println("Laptop Not Match:" + laptopNotMatch);

        Headphones headphones1 = new Headphones();
        headphones1.setHeadphones("Sony","Over-ear",true,true);
        System.out.println(headphones1);
        Headphones headphones2 = new Headphones();
        headphones2.setHeadphones("Bose","In-ear",true,false);
        System.out.println(headphones2);
        Headphones headphones3 = new Headphones();
        headphones3.setHeadphones("Bose","In-ear",true,false);
        System.out.println(headphones3);
        boolean headphonesMatch = headphones1.equals(headphones2);
        boolean headphonesNotMatch = headphones2.equals(headphones3);
        System.out.println("Headphones Match: "+ headphonesMatch);
        System.out.println("Headphones Not Match:" + headphonesNotMatch);

        Camera camera1 = new Camera();
        camera1.setCamera("Canon","EOS R5",45,true);
        System.out.println(camera1);
        Camera camera2 = new Camera();
        camera2.setCamera("Sony","A7 III",24,true);
        System.out.println(camera2);
        Camera camera3 = new Camera();
        camera3.setCamera("Sony","A7 III",24,true);
        System.out.println(camera3);
        boolean cameraMatch = camera1.equals(camera2);
        boolean cameraNotMatch = camera2.equals(camera3);
        System.out.println("Camera Match: "+ cameraMatch);
        System.out.println("Camera Not Match:" + cameraNotMatch);

        Television television1 = new Television();
        television1.setTelevision("Samsung",55,"4K",true);
        System.out.println(television1);
        Television television2 = new Television();
        television2.setTelevision("LG",65,"8K",true);
        System.out.println(television2);
        Television television3 = new Television();
        television3.setTelevision("LG",65,"8K",true);
        System.out.println(television3);
        boolean televisionMatch = television1.equals(television2);
        boolean televisionNotMatch = television2.equals(television3);
        System.out.println("Television Match: "+ televisionMatch);
        System.out.println("Television Not Match:" + televisionNotMatch);

        Refrigerator refrigerator1 = new Refrigerator();
        refrigerator1.setRefrigerator("Whirlpool",20.5,2,true);
        System.out.println(refrigerator1);
        Refrigerator refrigerator2 = new Refrigerator();
        refrigerator2.setRefrigerator("LG",18.0,1,false);
        System.out.println(refrigerator2);
        Refrigerator refrigerator3 = new Refrigerator();
        refrigerator3.setRefrigerator("LG",18.0,1,false);
        System.out.println(refrigerator3);
        boolean refrigeratorMatch = refrigerator1.equals(refrigerator2);
        boolean refrigeratorNotMatch = refrigerator2.equals(refrigerator3);
        System.out.println("Refrigerator Match: "+ refrigeratorMatch);
        System.out.println("Refrigerator Not Match:" + refrigeratorNotMatch);

        Microwave microwave1 = new Microwave();
        microwave1.setMicrowave("Panasonic",1.2,900,true);
        System.out.println(microwave1);
        Microwave microwave2 = new Microwave();
        microwave2.setMicrowave("Samsung",0.9,800,false);
        System.out.println(microwave2);
        Microwave microwave3 = new Microwave();
        microwave3.setMicrowave("Samsung",0.9,800,false);
        System.out.println(microwave3);
        boolean microwaveMatch = microwave1.equals(microwave2);
        boolean microwaveNotMatch = microwave2.equals(microwave3);
        System.out.println("Microwave Match: "+ microwaveMatch);
        System.out.println("Microwave Not Match:" + microwaveNotMatch);

        WashingMachine washingMachine1 = new WashingMachine();
        washingMachine1.setWashingMachine("LG",7.5,"Front Load",1200);
        System.out.println(washingMachine1);
        WashingMachine washingMachine2 = new WashingMachine();
        washingMachine2.setWashingMachine("Samsung",8.0,"Top Load",1000);
        System.out.println(washingMachine2);
        WashingMachine washingMachine3 = new WashingMachine();
        washingMachine3.setWashingMachine("Samsung",8.0,"Top Load",1000);
        System.out.println(washingMachine3);
        boolean washingMachineMatch = washingMachine1.equals(washingMachine2);
        boolean washingMachineNotMatch = washingMachine2.equals(washingMachine3);
        System.out.println("WashingMachine Match: "+ washingMachineMatch);
        System.out.println("WashingMachine Not Match:" + washingMachineNotMatch);

        AirConditioner airConditioner1 = new AirConditioner();
        airConditioner1.setAirConditioner("Daikin",1.5,"Split",true);
        System.out.println(airConditioner1);
        AirConditioner airConditioner2 = new AirConditioner();
        airConditioner2.setAirConditioner("Voltas",2.0,"Window",false);
        System.out.println(airConditioner2);
        AirConditioner airConditioner3 = new AirConditioner();
        airConditioner3.setAirConditioner("Voltas",2.0,"Window",false);
        System.out.println(airConditioner3);
        boolean airConditionerMatch = airConditioner1.equals(airConditioner2);
        boolean airConditionerNotMatch = airConditioner2.equals(airConditioner3);
        System.out.println("AirConditioner Match: "+ airConditionerMatch);
        System.out.println("AirConditioner Not Match:" + airConditionerNotMatch);

        VacuumCleaner vacuumCleaner1 = new VacuumCleaner();
        vacuumCleaner1.setVacuumCleaner("Dyson","Stick",2000,true);
        System.out.println(vacuumCleaner1);
        VacuumCleaner vacuumCleaner2 = new VacuumCleaner();
        vacuumCleaner2.setVacuumCleaner("Eureka","Canister",1500,false);
        System.out.println(vacuumCleaner2);
        VacuumCleaner vacuumCleaner3 = new VacuumCleaner();
        vacuumCleaner3.setVacuumCleaner("Eureka","Canister",1500,false);
        System.out.println(vacuumCleaner3);
        boolean vacuumCleanerMatch = vacuumCleaner1.equals(vacuumCleaner2);
        boolean vacuumCleanerNotMatch = vacuumCleaner2.equals(vacuumCleaner3);
        System.out.println("VacuumCleaner Match: "+ vacuumCleanerMatch);
        System.out.println("VacuumCleaner Not Match:" + vacuumCleanerNotMatch);

        Bicycle bicycle1 = new Bicycle();
        bicycle1.setBicycle("Hero","Mountain",21,true);
        System.out.println(bicycle1);
        Bicycle bicycle2 = new Bicycle();
        bicycle2.setBicycle("Atlas","Road",7,false);
        System.out.println(bicycle2);
        Bicycle bicycle3 = new Bicycle();
        bicycle3.setBicycle("Atlas","Road",7,false);
        System.out.println(bicycle3);
        boolean bicycleMatch = bicycle1.equals(bicycle2);
        boolean bicycleNotMatch = bicycle2.equals(bicycle3);
        System.out.println("Bicycle Match: "+ bicycleMatch);
        System.out.println("Bicycle Not Match:" + bicycleNotMatch);

        Car car1 = new Car();
        car1.setCar("Toyota","Camry",2022,"Petrol");
        System.out.println(car1);
        Car car2 = new Car();
        car2.setCar("Honda","Civic",2021,"Hybrid");
        System.out.println(car2);
        Car car3 = new Car();
        car3.setCar("Honda","Civic",2021,"Hybrid");
        System.out.println(car3);
        boolean carMatch = car1.equals(car2);
        boolean carNotMatch = car2.equals(car3);
        System.out.println("Car Match: "+ carMatch);
        System.out.println("Car Not Match:" + carNotMatch);

        Motorcycle motorcycle1 = new Motorcycle();
        motorcycle1.setMotorcycle("Royal Enfield","Classic 350",350,"Cruiser");
        System.out.println(motorcycle1);
        Motorcycle motorcycle2 = new Motorcycle();
        motorcycle2.setMotorcycle("Bajaj","Pulsar",220,"Sports");
        System.out.println(motorcycle2);
        Motorcycle motorcycle3 = new Motorcycle();
        motorcycle3.setMotorcycle("Bajaj","Pulsar",220,"Sports");
        System.out.println(motorcycle3);
        boolean motorcycleMatch = motorcycle1.equals(motorcycle2);
        boolean motorcycleNotMatch = motorcycle2.equals(motorcycle3);
        System.out.println("Motorcycle Match: "+ motorcycleMatch);
        System.out.println("Motorcycle Not Match:" + motorcycleNotMatch);

        Scooter scooter1 = new Scooter();
        scooter1.setScooter("Honda","Activa",110,false);
        System.out.println(scooter1);
        Scooter scooter2 = new Scooter();
        scooter2.setScooter("TVS","iQube",125,true);
        System.out.println(scooter2);
        Scooter scooter3 = new Scooter();
        scooter3.setScooter("TVS","iQube",125,true);
        System.out.println(scooter3);
        boolean scooterMatch = scooter1.equals(scooter2);
        boolean scooterNotMatch = scooter2.equals(scooter3);
        System.out.println("Scooter Match: "+ scooterMatch);
        System.out.println("Scooter Not Match:" + scooterNotMatch);

        Watch watch1 = new Watch();
        watch1.setWatch("Titan","Analog",true,false);
        System.out.println(watch1);
        Watch watch2 = new Watch();
        watch2.setWatch("Apple","Digital",true,true);
        System.out.println(watch2);
        Watch watch3 = new Watch();
        watch3.setWatch("Apple","Digital",true,true);
        System.out.println(watch3);
        boolean watchMatch = watch1.equals(watch2);
        boolean watchNotMatch = watch2.equals(watch3);
        System.out.println("Watch Match: "+ watchMatch);
        System.out.println("Watch Not Match:" + watchNotMatch);

        Backpack backpack1 = new Backpack();
        backpack1.setBackpack("Wildcraft",30,true,3);
        System.out.println(backpack1);
        Backpack backpack2 = new Backpack();
        backpack2.setBackpack("American Tourister",25,false,2);
        System.out.println(backpack2);
        Backpack backpack3 = new Backpack();
        backpack3.setBackpack("American Tourister",25,false,2);
        System.out.println(backpack3);
        boolean backpackMatch = backpack1.equals(backpack2);
        boolean backpackNotMatch = backpack2.equals(backpack3);
        System.out.println("Backpack Match: "+ backpackMatch);
        System.out.println("Backpack Not Match:" + backpackNotMatch);

        Sunglasses sunglasses1 = new Sunglasses();
        sunglasses1.setSunglasses("Ray-Ban","Black","Metal",true);
        System.out.println(sunglasses1);
        Sunglasses sunglasses2 = new Sunglasses();
        sunglasses2.setSunglasses("Oakley","Brown","Plastic",false);
        System.out.println(sunglasses2);
        Sunglasses sunglasses3 = new Sunglasses();
        sunglasses3.setSunglasses("Oakley","Brown","Plastic",false);
        System.out.println(sunglasses3);
        boolean sunglassesMatch = sunglasses1.equals(sunglasses2);
        boolean sunglassesNotMatch = sunglasses2.equals(sunglasses3);
        System.out.println("Sunglasses Match: "+ sunglassesMatch);
        System.out.println("Sunglasses Not Match:" + sunglassesNotMatch);

        Shoes shoes1 = new Shoes();
        shoes1.setShoes("Nike","Running",10,"Black");
        System.out.println(shoes1);
        Shoes shoes2 = new Shoes();
        shoes2.setShoes("Adidas","Casual",9,"White");
        System.out.println(shoes2);
        Shoes shoes3 = new Shoes();
        shoes3.setShoes("Adidas","Casual",9,"White");
        System.out.println(shoes3);
        boolean shoesMatch = shoes1.equals(shoes2);
        boolean shoesNotMatch = shoes2.equals(shoes3);
        System.out.println("Shoes Match: "+ shoesMatch);
        System.out.println("Shoes Not Match:" + shoesNotMatch);

        Jacket jacket1 = new Jacket();
        jacket1.setJacket("Columbia","Polyester","M",true);
        System.out.println(jacket1);
        Jacket jacket2 = new Jacket();
        jacket2.setJacket("The North Face","Nylon","L",false);
        System.out.println(jacket2);
        Jacket jacket3 = new Jacket();
        jacket3.setJacket("The North Face","Nylon","L",false);
        System.out.println(jacket3);
        boolean jacketMatch = jacket1.equals(jacket2);
        boolean jacketNotMatch = jacket2.equals(jacket3);
        System.out.println("Jacket Match: "+ jacketMatch);
        System.out.println("Jacket Not Match:" + jacketNotMatch);

        Jeans jeans1 = new Jeans();
        jeans1.setJeans("Levi's","Slim",32,"Blue");
        System.out.println(jeans1);
        Jeans jeans2 = new Jeans();
        jeans2.setJeans("Wrangler","Regular",34,"Black");
        System.out.println(jeans2);
        Jeans jeans3 = new Jeans();
        jeans3.setJeans("Wrangler","Regular",34,"Black");
        System.out.println(jeans3);
        boolean jeansMatch = jeans1.equals(jeans2);
        boolean jeansNotMatch = jeans2.equals(jeans3);
        System.out.println("Jeans Match: "+ jeansMatch);
        System.out.println("Jeans Not Match:" + jeansNotMatch);

        TShirt tShirt1 = new TShirt();
        tShirt1.setTShirt("Puma","M","Red","Round");
        System.out.println(tShirt1);
        TShirt tShirt2 = new TShirt();
        tShirt2.setTShirt("Under Armour","L","Black","V-neck");
        System.out.println(tShirt2);
        TShirt tShirt3 = new TShirt();
        tShirt3.setTShirt("Under Armour","L","Black","V-neck");
        System.out.println(tShirt3);
        boolean tShirtMatch = tShirt1.equals(tShirt2);
        boolean tShirtNotMatch = tShirt2.equals(tShirt3);
        System.out.println("TShirt Match: "+ tShirtMatch);
        System.out.println("TShirt Not Match:" + tShirtNotMatch);

        Hat hat1 = new Hat();
        hat1.setHat("Nike","Baseball","M","Blue");
        System.out.println(hat1);
        Hat hat2 = new Hat();
        hat2.setHat("Adidas","Bucket","L","Black");
        System.out.println(hat2);
        Hat hat3 = new Hat();
        hat3.setHat("Adidas","Bucket","L","Black");
        System.out.println(hat3);
        boolean hatMatch = hat1.equals(hat2);
        boolean hatNotMatch = hat2.equals(hat3);
        System.out.println("Hat Match: "+ hatMatch);
        System.out.println("Hat Not Match:" + hatNotMatch);

        Gloves gloves1 = new Gloves();
        gloves1.setGloves("Mountain Hardwear","Leather","M",true);
        System.out.println(gloves1);
        Gloves gloves2 = new Gloves();
        gloves2.setGloves("The North Face","Wool","L",false);
        System.out.println(gloves2);
        Gloves gloves3 = new Gloves();
        gloves3.setGloves("The North Face","Wool","L",false);
        System.out.println(gloves3);
        boolean glovesMatch = gloves1.equals(gloves2);
        boolean glovesNotMatch = gloves2.equals(gloves3);
        System.out.println("Gloves Match: "+ glovesMatch);
        System.out.println("Gloves Not Match:" + glovesNotMatch);

        Umbrella umbrella1 = new Umbrella();
        umbrella1.setUmbrella("GustBuster","Golf",8,true);
        System.out.println(umbrella1);
        Umbrella umbrella2 = new Umbrella();
        umbrella2.setUmbrella("Totes","Compact",6,false);
        System.out.println(umbrella2);
        Umbrella umbrella3 = new Umbrella();
        umbrella3.setUmbrella("Totes","Compact",6,false);
        System.out.println(umbrella3);
        boolean umbrellaMatch = umbrella1.equals(umbrella2);
        boolean umbrellaNotMatch = umbrella2.equals(umbrella3);
        System.out.println("Umbrella Match: "+ umbrellaMatch);
        System.out.println("Umbrella Not Match:" + umbrellaNotMatch);

        Wallet wallet1 = new Wallet();
        wallet1.setWallet("Fossil","Leather",6,true);
        System.out.println(wallet1);
        Wallet wallet2 = new Wallet();
        wallet2.setWallet("Tommy Hilfiger","Canvas",4,false);
        System.out.println(wallet2);
        Wallet wallet3 = new Wallet();
        wallet3.setWallet("Tommy Hilfiger","Canvas",4,false);
        System.out.println(wallet3);
        boolean walletMatch = wallet1.equals(wallet2);
        boolean walletNotMatch = wallet2.equals(wallet3);
        System.out.println("Wallet Match: "+ walletMatch);
        System.out.println("Wallet Not Match:" + walletNotMatch);
        
    }
}
